### ISSUE TITLE
undefined in modifier interpreted as string

### ISSUE THREAD

**Issue by floatdrop** [azproduction/b_#3]
Is this expected to be so:

``` js
b('button', { size: undefined })
// 'button button_size_undefined'
```

Shouldn't it be `button button_size` or `button`?

**Comment by azproduction** [comment]
Mod value could be bool or string. The rest is casted to string.
https://github.com/azproduction/b_/blob/master/index.js#L71

``` js
b('button', { size: false }) === 'button';
b('button', { size: true }) === 'button_size';
b('button', { size: 'xl' }) === 'button_size_xl';
b('button', { size: 9 }) === 'button_size_9';
b('button', { size: undefined }) === 'button_size_undefined'; // ?
b('button', { size: null }) === 'button_size_null'; // ?
b('button', { size: NaN }) === 'button_size_NaN'; // ?
```

Let's discuss the edge-cases: NaN, null and undefined.

**Comment by floatdrop** [comment]
I have this usecase in React:

``` js
var classes = b('y-button', {
    size: this.props.size
});
```

What I expected to see (when props size is undefined) is `y-button`. For now I use this snippet to achieve this:

``` js
var classes = b('y-button', {
    size: this.props.size || false
});
```

`null` or `NaN` are explicit values, so I guess it is ok to stringify them.

**Comment by azproduction** [comment]
React's class addon uses filter https://github.com/facebook/react/blob/5d3b12bb3bd6a092cf00ede07b8255a8399c2e58/src/vendor/stubs/cx.js which is uses ToBoolean http://www.ecma-international.org/ecma-262/5.1/#sec-9.2

| Argument Type | Result |
| --- | --- |
| Undefined | false |
| Null | false |
| Boolean | The result equals the input argument (no conversion). |
| Number | The result is false if the argument is +0, −0, or NaN; otherwise the result is true. |
| String | The result is false if the argument is the empty String (its length is zero); otherwise the result is true. |
| Object | true |

We could use the similar table with the string/number exception.

``` js
var isNonEmptyString = typeof modVal === 'string' && Boolean(modVal);
var isRealNumber = typeof modVal === 'number' && !isNaN(modVal);
modVal = (isNonEmptyString || isRealNumber) ? String(modVal) : Boolean(modVal);
```

``` js
b('button', { size: false }) === 'button';
b('button', { size: true }) === 'button_size';
b('button', { size: 'xl' }) === 'button_size_xl';
b('button', { size: '' }) === 'button';
b('button', { size: 9 }) === 'button_size_9';
b('button', { size: 0 }) === 'button_size_0';
b('button', { size: undefined }) === 'button';
b('button', { size: null }) === 'button';
b('button', { size: NaN }) === 'button';
```

The question is what to do with `Infinity` and should we respect zeros or cast them to bool?

**Comment by floatdrop** [comment]
Isn't it a bit too much magic? What if I have numerical modifier that can be `NaN` - and should be styled differently - then I should write ugly if: `val === NaN ? 'NaN' : val`. And `null` often is expected value, that used in API's.

My point is - most of the `undefined` occurrence happens from access to undefined properties (as with `this.props`) - so most of the time you will need to default it to falsy value. But with `null` and `NaN` this guess is false.

**Comment by azproduction** [comment]
> Isn't it a bit too much magic?

Yes, I also think so.

If I cast `undefined` to `false` then I would have to apply the same rule for `NaN` and `null` because they are also falsy values. Then the problem is what to do with `0` it pretty much okish value but falsy :/

**Comment by azproduction** [comment]
On the other hand `undefined` could be an implicit value, as you mentioned. And null and NaN are 100% user defined.

**Comment by floatdrop** [comment]
> On the other hand undefined could be an implicit value, as you mentioned.

Yep, but it's about what case is more common - I think in 99% `undefined` is not expected to convert into `block_mod_undefined`, but to `block`. For other cases you still can add `val === undefined ? 'undefined' : val` workaround.

**Comment by azproduction** [comment]
So the final spec:

``` js
b('button', { size: false }) === 'button';
b('button', { size: true }) === 'button_size';
b('button', { size: 'xl' }) === 'button_size_xl';
b('button', { size: '' }) === 'button'; // <<< diff
b('button', { size: 9 }) === 'button_size_9';
b('button', { size: 0 }) === 'button_size_0';
b('button', { size: undefined }) === 'button'; // <<< diff
b('button', { size: null }) === 'button_size_null';
b('button', { size: NaN }) === 'button_size_NaN';
```

I'll cast empty strings and undefined to false so it will drop modifier.

**Comment by floatdrop** [comment]
I'm not sure about this:

``` js
b('button', { size: '' }) === 'button';
```

I would go only with `undefined` as special case. I've asked devs around and no one use `''` in code for modifiers.

**Comment by azproduction** [comment]
Anyway it is "illegal" to have an empty mod value. And we can filter it out

``` js
b('button', { size: '' }) === 'button_size_'; // <<< current value
```

**Comment by azproduction** [comment]
But we could be consistant with https://github.com/ingdir/jquery-bemhelpers/ and allow empty modifiers:

``` js
$('body').setMod('pewpew', 'ololo', 'mod', '').hasClass('pewpew__ololo_mod_');
```

**Comment by azproduction** [comment]
I'll keep empty strings as is for now and I'll take care of `undefined`.

**Comment by floatdrop** [comment]
@azproduction :+1:

**Comment by azproduction** [comment]
npm `b_@1.2.0`

**Comment by floatdrop** [comment]
Nice!
