### ISSUE TITLE
ie8 throws error on the `b.with` line

### ISSUE THREAD

**Issue by gitim** [azproduction/b_#6]
Hi! I am using b_ in my project and including it into bundles. There is a problem in ie8, it errors when running the `b.with` line of the b_:
![2015-04-29 2 16 18](https://cloud.githubusercontent.com/assets/3778452/7382539/e1f17eac-ee18-11e4-9dab-d5114ee5b1c9.png)
and here the 274th line of my bundle, this function is from b_ module
![2015-04-29 2 16 43](https://cloud.githubusercontent.com/assets/3778452/7382540/e430473e-ee18-11e4-87c8-c5859b093049.png)
Replacing all `b.with` with `b['with']` solves the problem, but `var bem = require('b_')['with']('myBlock');` looks not so good. It seems that `.with` function should be renamed.

**Comment by azproduction** [comment]
Thanks for reporting.

`b_@1.3.1`

``` js
require('b_').lock('b-smth');
```

**Comment by gitim** [comment]
Thanks, now it works fine :+1:
