### ISSUE TITLE
license

### ISSUE THREAD

**Issue by iamstarkov** [azproduction/b_#8]
there is no license declared for this project. its kinda a problem

**Comment by azproduction** [comment]
https://github.com/azproduction/b_/blob/master/LICENSE ?

**Comment by iamstarkov** [comment]
oh, missed this file, sorry. can you add note about license also in package.json and readme files?

**Comment by azproduction** [comment]
`b_@1.3.3` IMO, it implies that LICENSE is defining the license, so no reason to mention it in README.

**Comment by iamstarkov** [comment]
okie, but it is common place for license declaration

**Comment by iamstarkov** [comment]
thank you for publishing new version
